import {test,expect} from '@playwright/test';
import path from 'node:path';
test('完整验收：预览导入、选2/4课、学习、生词、忽略、统计、刷新和复习',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:'今天，也学一点吧。'})).toBeVisible();await page.screenshot({path:'docs/screenshots/home-desktop.png',fullPage:true,animations:"disabled"});
 await page.getByRole('link',{name:'导入我的词书'}).click();await page.locator('input[type=file]').setInputFiles(path.resolve('examples/demo.csv'));await expect(page.getByText('4 个课次',{exact:true})).toBeVisible();await page.getByLabel('词书名称').fill('端到端验收词书');await page.getByRole('button',{name:'确认导入'}).click();await expect(page.getByRole('heading',{name:'端到端验收词书'})).toBeVisible();
 await page.getByRole('checkbox').nth(1).check();await page.getByRole('checkbox').nth(3).check();await page.getByRole('button',{name:'开始学习所选课程'}).click();await expect(page.getByRole('heading',{name:'本',exact:true})).toBeVisible();await page.getByRole('button',{name:'加入生词本'}).click();await page.getByRole('button',{name:'显示释义'}).click();await expect(page.getByRole('heading',{name:'书',exact:true})).toBeVisible();await page.screenshot({path:'docs/screenshots/study-desktop.png',fullPage:true,animations:"disabled"});await page.getByRole('button',{name:'忘记了'}).click();await expect(page.getByRole('heading',{name:'机',exact:true})).toBeVisible();await page.getByRole('button',{name:'忽略此词'}).click();
 for(let i=0;i<22;i++){await expect(page.locator('.study-top')).toContainText(/第[24]课/);await page.getByRole('button',{name:'显示释义'}).click();await page.getByRole('button',{name:'记得',exact:false}).click()}
 await expect(page.getByRole('heading',{name:'这一小步，已经记下。'})).toBeVisible();await page.getByRole('link',{name:'回到今日'}).click();await expect(page.locator('.metric-row').first()).toContainText('23');await page.reload();await expect(page.locator('.metric-row').first()).toContainText('23');
 await page.getByRole('link',{name:'生词本',exact:true}).click();await expect(page.locator('.word-row')).toHaveCount(1);await page.getByRole('link',{name:'忽略列表',exact:true}).click();await expect(page.locator('.word-row')).toContainText('机');await page.getByRole('button',{name:'恢复学习'}).click();await expect(page.locator('.word-row')).toHaveCount(0);
 await page.getByRole('link',{name:'学习统计',exact:true}).click();await expect(page.locator('.metric-row')).toContainText('23');
 // Advance the browser clock to exercise real FSRS due times, without mutating persisted states.
 await page.clock.install();await page.clock.fastForward(16*60*1000);await page.getByRole('link',{name:'今日',exact:true}).click();await page.getByRole('button',{name:'开始今日复习'}).click();await expect(page.locator('.study-top')).toContainText('到期复习');await expect(page.locator('.word-face')).toBeVisible();expect(errors).toEqual([]);
});
test('移动端、JSON 导入、编辑删除、空列表',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.getByRole('heading',{name:'今天，也学一点吧。'})).toBeVisible();await page.screenshot({path:'docs/screenshots/home-mobile.png',fullPage:true,animations:"disabled"});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('link',{name:'导入我的词书'}).click();await page.locator('input[type=file]').setInputFiles(path.resolve('examples/demo.json'));await page.getByLabel('词书名称').fill('JSON验收');await page.getByRole('button',{name:'确认导入'}).click();await page.getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('词书名称').fill('已编辑');await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByRole('heading',{name:'已编辑'})).toBeVisible();await page.getByRole('button',{name:'全选',exact:true}).click();await page.getByRole('button',{name:'反选',exact:true}).click();await expect(page.getByRole('checkbox').first()).not.toBeChecked();await page.screenshot({path:'docs/screenshots/book-mobile.png',fullPage:true,animations:"disabled"});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'删除词书'}).click();await page.getByRole('button',{name:'确认删除'}).click();await expect(page.getByRole('heading',{name:'我的词书'})).toBeVisible();await expect(page.getByRole('heading',{name:'已编辑'})).toHaveCount(0);
});
