<script setup lang="ts">
import {ref,watch,computed} from 'vue';import type {Word} from '@jp/models';import {dictionary} from '../services/dictionary';import {partOfSpeechLabel,type DictionaryEntry} from '@jp/dictionary';
import examples from '../learning-examples.json';
const props=defineProps<{word:Word}>();const entries=ref<DictionaryEntry[]>([]);const loading=ref(false);const failed=ref(false);const expanded=ref(false);let request=0;
const sample=computed(()=>(examples as Record<string,{ja:string;reading:string;zh:string}>)[`${props.word.term}|${props.word.reading}`]);
const localSenses=computed(()=>props.word.senses?.length?props.word.senses:[{meaning:props.word.meaning,partOfSpeech:props.word.partOfSpeech,definitionJa:props.word.definitionJa}]);
async function lookup(){const ticket=++request;loading.value=true;failed.value=false;entries.value=[];try{const result=await dictionary.lookup(props.word.term,props.word.reading);if(ticket===request)entries.value=result}catch{if(ticket===request)failed.value=true}finally{if(ticket===request)loading.value=false}}
watch(()=>props.word.id,()=>{expanded.value=false;lookup()},{immediate:true});
</script>
<template><section class="definition-panel" aria-label="单词详细释义"><div class="definition-heading"><h2>释义</h2><span>词书释义</span></div><div v-for="(sense,i) in localSenses" :key="i" class="local-sense"><div><span v-if="sense.partOfSpeech" class="pos-tag">{{sense.partOfSpeech}}</span><span v-if="localSenses.length>1" class="sense-number">{{i+1}}.</span><h2>{{sense.meaning}}</h2></div><p v-if="sense.definitionJa" lang="ja">{{sense.definitionJa}}</p><p v-if="sense.example" lang="ja">{{sense.example}}</p><p v-if="sense.exampleReading" class="muted">{{sense.exampleReading}}</p><p v-if="sense.exampleTranslation">{{sense.exampleTranslation}}</p></div><p v-if="word.definitionZh">{{word.definitionZh}}</p>
<div class="dictionary-section"><div class="definition-heading"><h3>词典扩展</h3><span>日中 · 日文释义</span></div><p v-if="loading" role="status" class="muted">正在查找词典…</p><div v-else-if="failed" class="dictionary-message" role="status">词典暂时加载失败，词书释义仍可使用。<button @click="lookup">重试</button></div><p v-else-if="!entries.length" class="muted">未找到与「{{word.term}} · {{word.reading}}」完全匹配的词条，可查阅下方辞典。</p><template v-else><article v-for="entry in entries" :key="entry.id" class="dictionary-entry"><h4 v-if="entries.length>1">{{entry.terms.join(' / ')||word.term}} <small>{{entry.readings.map(r=>r.text).join(' / ')}}</small></h4><ol><li v-for="(sense,i) in (expanded?entry.senses:entry.senses.slice(0,3))" :key="i"><span class="pos-tag">{{partOfSpeechLabel(sense.pos)}}</span><p class="sense-zh">{{sense.zh.join('；')||'此义项暂无中文译文'}}</p><p v-if="sense.en.length" class="sense-en" lang="en">{{sense.en.join('; ')}}</p></li></ol><div v-for="(definition,i) in entry.japanese" :key="i" class="japanese-definition"><div class="definition-heading"><strong>日文解释</strong><span>{{definition.source==='wiktionary'?'维基词典 · 社区编纂':'机器辅助释义'}}</span></div><p v-for="(text,j) in (expanded?definition.texts:definition.texts.slice(0,3))" :key="j" lang="ja">{{text}}</p></div></article><button v-if="entries.some(e=>e.senses.length>3||e.japanese.some(d=>d.texts.length>3))" class="expand-senses" @click="expanded=!expanded">{{expanded?'收起部分义项':'展开全部义项'}}</button><p class="dictionary-credit">词条依据 <a href="https://www.edrdg.org/edrdg/licence.html" target="_blank" rel="noopener noreferrer">JMdict / EDRDG</a>；中文及日文扩展来自 <a href="https://github.com/tomoshi-app/tomoshi-dict-data" target="_blank" rel="noopener noreferrer">Tomoshi (Y1Z)</a>，含机器辅助译释，并非出版社审定。<a href="/dictionary/KOTOBA-NOTICE.md" target="_blank">来源声明</a> · <a href="/dictionary/LICENSE.md" target="_blank">CC BY-SA 4.0</a></p></template></div>
<section v-if="word.example||sample" class="example-section"><div class="definition-heading"><h3>单词例句</h3><span>{{word.example?'词书提供':'KotoBud 学习例句 · 非辞典原文'}}</span></div><p class="example-ja" lang="ja">{{word.example||sample?.ja}}</p><p class="example-reading" lang="ja">{{word.example?word.exampleReading:sample?.reading}}</p><p>{{word.example?word.exampleTranslation:sample?.zh}}</p></section><p v-if="word.note" class="word-note">笔记 · {{word.note}}</p><div class="reference-links"><span>查阅权威辞典</span><a :href="'https://kotobank.jp/search?word='+encodeURIComponent(word.term)+'&t=all'" target="_blank" rel="noopener noreferrer">コトバンク ↗</a><small>在原网站查看出版社辞典内容</small></div></section></template>
