<script setup lang="ts">
import {computed,ref,watch} from 'vue';import {useRoute,useRouter} from 'vue-router';import {ArrowLeft,ArrowRight} from 'lucide-vue-next';import {useApp} from '../store';import {progress,selectRange,stateFor} from '@jp/core';
const app=useApp();const route=useRoute();const router=useRouter();const book=computed(()=>app.data.books.find(b=>b.id===route.params.id));const lessons=computed(()=>app.data.lessons.filter(l=>l.bookId===book.value?.id).sort((a,b)=>a.order-b.order));const selected=ref<string[]>([]);const from=ref(1);const to=ref(2);watch(lessons,value=>{if(value.length){from.value=value[0].order;to.value=value[Math.min(1,value.length-1)].order}},{immediate:true});const editing=ref(false);const title=ref('');const desc=ref('');const deleting=ref(false);const expanded=ref('');
watch(()=>route.params.id,async id=>{if(typeof id==='string')await app.ensureBookLoaded(id)},{immediate:true});
watch(()=>route.query.lesson,value=>{if(typeof value==='string'&&lessons.value.some(l=>l.id===value))selected.value=[value]},{immediate:true});
const words=(id:string)=>app.data.words.filter(w=>w.lessonId===id);const lessonProgress=(id:string)=>progress(app.data,words(id));const count=computed(()=>app.data.words.filter(w=>selected.value.includes(w.lessonId)&&!stateFor(app.data,w.id)?.firstSeenAt&&!stateFor(app.data,w.id)?.isIgnored).length);
function edit(){title.value=book.value?.title??'';desc.value=book.value?.description??'';editing.value=true}async function save(){if(book.value&&await app.editBook(book.value.id,title.value,desc.value))editing.value=false}async function remove(){if(book.value&&await app.removeBook(book.value.id))router.push('/books')}async function start(){await app.start('new',selected.value,book.value?.id);router.push('/study')}
</script>
<template><template v-if="book"><RouterLink to="/books" class="back"><ArrowLeft :size="16"/> 我的词书</RouterLink><section class="page-heading"><div><p class="eyebrow">JAPANESE COLLECTION</p><h1>{{book.title}}</h1><p class="muted">{{book.description||'选一课，从这里开始。'}}</p></div><div class="actions"><button @click="edit">编辑</button><button class="danger-text" @click="deleting=true">删除词书</button></div></section><form v-if="editing" class="form-panel" @submit.prevent="save"><label>词书名称<input v-model="title" required maxlength="100"/></label><label>简介<textarea v-model="desc"/></label><div class="actions"><button class="primary" :disabled="app.busy">保存</button><button type="button" @click="editing=false">取消</button></div></form><div v-if="deleting" class="error" role="alert"><p>删除「{{book.title}}」及其学习记录？此操作无法撤销。</p><button :disabled="app.busy" @click="remove">确认删除</button> <button @click="deleting=false">取消</button></div><div class="section-title"><h2>自由选择课次 <small>{{lessons.length}} 课</small></h2><span class="muted">无需按顺序解锁</span></div><div class="selection-tools"><div class="actions"><button @click="selected=lessons.map(l=>l.id)">全选</button><button @click="selected=lessons.filter(l=>!selected.includes(l.id)).map(l=>l.id)">反选</button></div><div class="actions"><label>从 <select v-model="from"><option v-for="l in lessons" :value="l.order">{{l.order}} 课</option></select></label><label>到 <select v-model="to"><option v-for="l in lessons" :value="l.order">{{l.order}} 课</option></select></label><button @click="selected=selectRange(lessons,from,to)">选择范围</button></div></div><div class="lessons"><div v-for="l in lessons" :key="l.id" class="lesson-row" :class="{selected:selected.includes(l.id)}"><label class="lesson-select"><input type="checkbox" v-model="selected" :value="l.id"/><span class="lesson-number">{{String(l.order).padStart(2,'0')}}</span><span><strong>{{l.title}}</strong><small>{{words(l.id).length}} 词 · 已学 {{lessonProgress(l.id).learned}} · 掌握 {{lessonProgress(l.id).mastered}}</small></span></label><div class="lesson-progress"><div class="progress"><i :style="{width:lessonProgress(l.id).percent+'%'}"></i></div><small>{{lessonProgress(l.id).percent}}%</small></div><button @click="expanded=expanded===l.id?'':l.id">{{expanded===l.id?'收起':'查看词汇'}}</button><div v-if="expanded===l.id" class="lesson-words"><div v-for="w in words(l.id)" :key="w.id"><strong lang="ja">{{w.term}}</strong><span>{{w.reading}}</span><span>{{w.meaning}}</span></div></div></div></div><div v-if="!lessons.length" class="empty">这是一本空词书。可以在导入页创建包含课次的新词书。<RouterLink to="/import">去导入 →</RouterLink></div><div class="selection-footer"><span>已选 <strong>{{selected.length}}</strong> 课 · {{count}} 个未学单词</span><button class="primary" :disabled="!count||app.busy" @click="start">开始学习所选课程 <ArrowRight :size="17"/></button></div></template><div v-else class="empty">找不到这本词书。<RouterLink to="/books">返回词书</RouterLink></div></template>
