<script setup lang="ts">
import {computed} from 'vue';import {useRouter} from 'vue-router';import {ArrowUpRight,ArrowRight,BookOpen,Flame} from 'lucide-vue-next';import {useApp} from '../store';import {progress} from '@jp/core';import WeekChart from '../components/WeekChart.vue';
const app=useApp();const router=useRouter();const book=computed(()=>app.data.books.find(b=>b.id===app.data.currentBookId)??app.data.books[0]);const bp=computed(()=>{const ids=app.data.lessons.filter(l=>l.bookId===book.value?.id).map(l=>l.id);const words=app.data.words.filter(w=>ids.includes(w.lessonId));if(words.length)return progress(app.data,words);const meta=app.metaBooks?.find(b=>b.id===book.value?.id);const total=meta?.wordCount??0;const learned=app.data.states.filter(s=>s.status!=='new'&&(s.firstSeenAt||s.reviewCount>0)).length;return{total,learned,mastered:app.data.states.filter(s=>s.status==='mastered').length,percent:total?Math.round(learned/total*100):0}});async function review(){await app.start('review');router.push('/study')}
const isWeb=window.location.protocol!=='kotoba:';
const windowsDownloadsReady=import.meta.env.VITE_WINDOWS_DOWNLOADS_READY==='true';
const hasProgress=computed(()=>app.data.logs.length>0||app.data.states.some(s=>!!s.firstSeenAt||s.reviewCount>0));
const learningTarget=computed(()=>{
 if(app.queue.length>app.index)return '/study';
 for(let i=app.data.logs.length-1;i>=0;i--){
  const word=app.data.words.find(w=>w.id===app.data.logs[i].wordId);
  const lesson=app.data.lessons.find(l=>l.id===word?.lessonId);
  if(lesson&&app.data.books.some(b=>b.id===lesson.bookId))return '/books/'+lesson.bookId+'?lesson='+encodeURIComponent(lesson.id);
 }
 return book.value?'/books/'+book.value.id:'/books';
});
</script>
<template><section class="page-heading"><div><p class="eyebrow">{{new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}}</p><h1>今天，也学一点吧。</h1><p class="muted">不用着急，每一个词都在让世界变得清晰。</p></div><span class="streak"><Flame :size="17"/> 连续学习 {{app.stats.streak}} 天</span></section><section class="today-panel"><div><p class="eyebrow">温故知新 · 今日复习</p><div class="due-number">{{app.stats.due}}<span>个单词，等你再见</span></div><p>让熟悉的词，留在记忆里。</p><div class="home-learning-actions"><RouterLink :to="learningTarget" class="button primary">{{hasProgress?'继续学习':'开始学习'}} <ArrowRight :size="18"/></RouterLink><button @click="review">查看复习队列 <ArrowRight :size="18"/></button></div></div><div class="jp-quote" lang="ja"><span>日々、</span><span>少しずつ。</span><small>每一天，一点点。</small></div></section><section class="metric-row"><div><span>今日新学</span><strong>{{app.stats.newToday}}<small>词</small></strong></div><div><span>今日复习</span><strong>{{app.stats.reviewToday}}<small>次</small></strong></div><div><span>累计学习</span><strong>{{app.stats.learned}}<small>词</small></strong></div><div><span>整体进度</span><strong>{{app.stats.percent}}<small>%</small></strong></div></section><div class="home-columns"><section><div class="section-title"><h2>继续你的词书</h2><RouterLink to="/books">全部词书 <ArrowUpRight :size="16"/></RouterLink></div><RouterLink v-if="book" :to="'/books/'+book.id" class="current-book"><div class="book-cover"><span>日本語</span><strong>言葉</strong><small>KotoBud COLLECTION</small></div><div><span class="eyebrow">正在学习</span><h3>{{book.title}}</h3><p class="muted">{{app.data.lessons.filter(l=>l.bookId===book.id).length}} 课 · {{bp.total}} 词</p><div class="progress"><i :style="{width:bp.percent+'%'}"></i></div><small>已学 {{bp.learned}} / {{bp.total}} 词</small><p class="text-action">选择课次，开始学习 <ArrowRight :size="16"/></p></div></RouterLink><div v-else class="empty">还没有词书。<RouterLink to="/import">导入第一本词书</RouterLink></div></section><section><div class="section-title"><h2>这一周的积累</h2><RouterLink to="/stats">详情 <ArrowUpRight :size="16"/></RouterLink></div><WeekChart :days="app.stats.days"/></section></div><div class="quiet-note"><BookOpen :size="18"/><span>从感兴趣的一课开始。所有课次，都可以自由选择。</span><RouterLink to="/import">导入我的词书 →</RouterLink></div><section v-if="isWeb" class="windows-download"><div><h2>下载 Windows 版</h2><p class="muted">KotoBud 0.6.0 · Windows x64 · 支持离线学习</p><p v-if="!windowsDownloadsReady" class="muted">安装包上传尚未完成，下载暂不可用。</p></div><div class="actions"><a class="button primary" :href="windowsDownloadsReady?'/downloads/Kotoba-0.6.0-Windows-x64-Setup.exe':undefined" :aria-disabled="!windowsDownloadsReady">下载安装版</a><a class="button" :href="windowsDownloadsReady?'/downloads/Kotoba-0.6.0-Windows-x64-Portable.exe':undefined" :aria-disabled="!windowsDownloadsReady">下载便携版</a></div></section></template>

<style scoped>
.home-learning-actions{display:flex;flex-direction:column;align-items:flex-start;gap:10px}.home-learning-actions .primary{min-width:180px}.windows-download{margin-top:28px;padding:24px 0;border-top:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap}.windows-download h2{margin:0 0 8px}.windows-download p{margin:0;font-size:13px}.windows-download .actions{flex-wrap:wrap}.windows-download [aria-disabled="true"]{opacity:.5;cursor:not-allowed}
</style>
