<script setup lang="ts">
import {computed,ref,shallowRef,watch,onMounted,onUnmounted,nextTick} from 'vue';
import {Bookmark,EyeOff,ArrowLeft,Check,Volume2} from 'lucide-vue-next';
import {useApp} from '../store';
import {stateFor,createQuestion,quizAttempt,quizRating,type Question} from '@jp/core';
import type {Grade} from 'ts-fsrs';import type {ExerciseType,QuizType,QuizAttempt} from '@jp/models';import {PRONUNCIATION_VOICES,type PronunciationVoice} from '../services/pronunciationPreference';
import WordDefinition from '../components/WordDefinition.vue';import QuizQuestion from '../components/QuizQuestion.vue';import {usePronunciation} from '../composables/usePronunciation';
const app=useApp();const pronunciation=usePronunciation();const voiceModel=pronunciation.voiceModel;const answer=ref(false);const started=ref(Date.now());const answeredIn=ref(0);const heard=ref(false);const uncertain=ref(false);
const exercise=ref<ExerciseType>(app.mode==='new'?'card':'mixed');const question=shallowRef<Question|null>(null);const attempt=shallowRef<QuizAttempt|null>(null);
const word=computed(()=>app.queue[app.index]);const state=computed(()=>word.value?stateFor(app.data,word.value.id):undefined);const lesson=computed(()=>app.data.lessons.find(l=>l.id===word.value?.lessonId));
const options:{value:ExerciseType;label:string}[]=[{value:'card',label:'经典卡片'},{value:'mixed',label:'混合复习'},{value:'kana-meaning',label:'假名选中文'},{value:'kanji-reading',label:'汉字选假名'},{value:'audio-meaning',label:'听音选中文'}];
const fallback=ref('');
function prepare(){
 pronunciation.stop();pronunciation.error.value='';answer.value=false;attempt.value=null;heard.value=false;uncertain.value=false;started.value=Date.now();question.value=null;fallback.value='';
 if(!word.value||exercise.value==='card')return;
 const pool=app.data.words.filter(w=>!stateFor(app.data,w.id)?.isIgnored);
 const types:QuizType[]=exercise.value==='mixed'?['kana-meaning','kanji-reading','audio-meaning']:[exercise.value];
 const rotated=exercise.value==='mixed'?types.slice(app.index%3).concat(types.slice(0,app.index%3)):types;
 for(const type of rotated){if(type==='audio-meaning'&&!pronunciation.available(word.value))continue;const candidate=createQuestion(word.value,pool,type);if(candidate){question.value=candidate;return}}
 fallback.value=exercise.value==='audio-meaning'?'这个词没有音频，设备也未提供日语语音。请切换题型。':exercise.value==='kanji-reading'&&!/\p{Script=Han}/u.test(word.value.term)?'这个词没有汉字，适合使用假名或听音题。':'没有足够的不重复选项，请切换经典卡片。';
}
watch([()=>word.value?.id,exercise],prepare,{immediate:true});
watch(()=>word.value?.id,async()=>{await nextTick();window.scrollTo({top:0})});
watch(pronunciation.hasJapaneseVoice,()=>{if(!attempt.value&&!question.value&&exercise.value!=='card')prepare()});
async function rate(rating:Grade){if(answer.value)await app.rate(rating,Date.now()-started.value)}
function choose(value:string|null){if(!question.value||attempt.value||app.busy)return;if(question.value.type==='audio-meaning'&&(!heard.value||pronunciation.error.value))return;attempt.value=quizAttempt(question.value,value);answeredIn.value=Date.now()-started.value;answer.value=true;pronunciation.stop()}
async function next(){if(!attempt.value||app.busy)return;await app.rate(quizRating(attempt.value,uncertain.value),answeredIn.value,attempt.value)}
async function difficult(){if(word.value)await app.flag(word.value.id,'isDifficult',!state.value?.isDifficult)}
async function ignore(){if(word.value&&!attempt.value&&await app.flag(word.value.id,'isIgnored',true))app.index++}
async function play(slow=false){if(!word.value)return;const id=word.value.id;if(await pronunciation.play(word.value,slow)&&word.value?.id===id)heard.value=true}
function changeVoice(event:Event){const value=(event.target as HTMLSelectElement).value as PronunciationVoice;pronunciation.setVoice(value);pronunciation.stop();pronunciation.error.value=''}
function key(e:KeyboardEvent){
 if(e.ctrlKey||e.altKey||e.metaKey||e.repeat||app.busy||!word.value)return;const target=e.target as HTMLElement;if(target.closest('input,textarea,select,[contenteditable="true"]'))return;
 const k=e.key.toLowerCase();if(k===' '){if(target.closest('button,a'))return;e.preventDefault();if(attempt.value)next();else if(question.value?.type==='audio-meaning')play();else if(exercise.value==='card')answer.value=true}
 else if(['1','2','3','4'].includes(k)){e.preventDefault();if(question.value&&!attempt.value){const option=question.value.options[Number(k)-1];if(option)choose(option)}else if(exercise.value==='card'&&Number(k)<=3)rate(Number(k) as Grade)}
 else if(k==='s'){e.preventDefault();difficult()}else if(k==='i'&&!attempt.value){e.preventDefault();ignore()}
}
onMounted(()=>window.addEventListener('keydown',key));onUnmounted(()=>window.removeEventListener('keydown',key));
</script>
<template><RouterLink to="/books" class="back"><ArrowLeft :size="16"/> 结束本次学习</RouterLink><template v-if="word"><div class="study-top"><span>{{app.mode==='new'?'学习新词':app.mode==='review'?'到期复习':'生词练习'}} · {{lesson?.title}}</span><span>{{app.index+1}} / {{app.sessionSize}}</span></div><div class="progress session-progress"><i :style="{width:(app.index/app.sessionSize*100)+'%'}"></i></div><div class="exercise-toolbar"><label>学习方式<select v-model="exercise" :disabled="!!attempt||app.busy"><option v-for="o in options" :key="o.value" :value="o.value">{{o.label}}</option></select></label><label>声音<select v-model="voiceModel" aria-label="发音声音" @change="changeVoice"><option v-for="voice in PRONUNCIATION_VOICES" :key="voice.value" :value="voice.value">{{voice.label}}</option></select></label><span>按 1–4 选择 · Space 继续</span></div><section class="study-card enhanced-study"><div class="card-top"><span class="eyebrow">{{exercise==='card'?'想一想，这个词是什么意思？':'从不同方向，记住一个词。'}}</span><button :class="{marked:state?.isDifficult}" :aria-pressed="!!state?.isDifficult" :disabled="app.busy" @click="difficult"><Bookmark :size="18"/>{{state?.isDifficult?'已加入生词':'加入生词本'}}</button></div>
<template v-if="exercise==='card'"><div class="word-face" lang="ja"><h1>{{word.term}}<sup v-if="word.accent">{{word.accent}}</sup></h1><p>{{word.reading}}</p></div><div class="pronunciation-controls"><template v-if="pronunciation.available(word)"><button @click="play()"><Volume2 :size="17"/> 发音</button><button @click="play(true)">慢速</button><small>{{pronunciation.sourceLabel(word)}}</small></template><span v-else class="muted">此词暂无可用日语发音</span></div><p v-if="pronunciation.error.value" class="error" role="alert">{{pronunciation.error.value}}</p><WordDefinition v-if="answer" :word="word"/><div v-else class="answer-placeholder">让记忆停留一会儿。</div><button v-if="!answer" class="primary reveal" @click="answer=true">显示释义 <kbd>Space</kbd></button><div v-else class="ratings sticky-ratings"><button :disabled="app.busy" class="again" @click="rate(1)"><span>忘记了</span><kbd>1</kbd></button><button :disabled="app.busy" class="hard" @click="rate(2)"><span>模糊</span><kbd>2</kbd></button><button :disabled="app.busy" class="good" @click="rate(3)"><span>记得</span><kbd>3</kbd></button></div></template>
<template v-else-if="question"><QuizQuestion :question="question" :attempt="attempt" :heard="heard" :busy="app.busy" :audio-error="pronunciation.error.value" :speaking="pronunciation.speaking.value" @choose="choose" @play="play"/><template v-if="attempt"><div class="revealed-word" lang="ja"><strong>{{word.term}}</strong><span>{{word.reading}}</span><button v-if="pronunciation.available(word)" aria-label="播放单词发音" @click="play()"><Volume2 :size="18"/></button></div><WordDefinition :word="word"/><div class="quiz-next"><label v-if="attempt.isCorrect"><input type="checkbox" v-model="uncertain"/> 这次是猜对的，下次早点复习</label><p v-else>本次记为「忘记」，将更早安排复习。</p><button class="primary" :disabled="app.busy" @click="next">保存并继续 <kbd>Space</kbd></button></div></template></template><div v-else class="empty"><p>{{fallback}}</p><button @click="exercise='card'">使用经典卡片</button></div></section><div class="study-bottom"><button :disabled="app.busy||!!attempt" @click="ignore"><EyeOff :size="17"/> 忽略此词 <kbd>I</kbd></button><span>{{attempt?'点击「保存并继续」记录本次答题':'标记生词 S · 已保存的进度不会丢失'}}</span></div></template><section v-else class="completion"><span class="completion-icon"><Check :size="34"/></span><p class="eyebrow">おつかれさま</p><h1>{{app.sessionSize?'这一小步，已经记下。':'现在没有待学单词。'}}</h1><p>{{app.sessionSize?`本次已处理 ${app.index} 个词。学习记录已保存，到了时间再来复习。`:'可以选择其他课次，或稍后回来查看到期复习。'}}</p><RouterLink to="/" class="button primary">回到今日</RouterLink><RouterLink to="/books" class="button">继续选课</RouterLink></section></template>
